### ISSUE TITLE
News/Blog page todo

### ISSUE THREAD

**Issue by zafarali** [bricobio/bricobio-website#6]
- [x] Posts show 'and' too many times
- [x] Too much space between the posts 
- [x] Too much space between the columns
- [x] Calendar looks very out of place (is it just me??)

**Comment by zafarali** [comment]
Calendar doesn't look too bad anymore.
